#ifndef USRINC_SMS_H_
#define USRINC_SMS_H_

//SMS Lists
#define SMS_READ_STATUS			"CMSE#STATUS"
#define SMS_READ_IP_CFG			"CMSE#IPR"
#define SMS_READ_FTP_CFG		"CMSE#FTPREAD"
#define SMS_READ_APNNAME1		"CMSE#APNREAD1"
#define SMS_READ_APNNAME2		"CMSE#APNREAD2"
#define SMS_READ_MODBUS_CFG		"CMSE#CHCONFIGREAD"
#define SMS_READ_PERI_TIME		"CMSE#GET PERI TIME"

#define SMS_WRITE_CLOUD_CFG		"CMSE#TCP2#"
#define SMS_WRITE_TIMER_CFG		"CMSE#TIME SER IP#"
#define SMS_WRITE_FTP_CFG		"CMSE#FTP#"
#define SMS_WRITE_APNNAME1		"CMSE#APNNAME1#"
#define SMS_WRITE_APNNAME2		"CMSE#APNNAME2#"
#define SMS_WRITE_PERI_TIME		"CMSE#PERI TIME#OTHERS#"


#define SMS_CLEAR_APNNAME1		"CMSE#APNCLEAR1"
#define SMS_CLEAR_APNNAME2		"CMSE#APNCLEAR2"
#define SMS_CLEAR_MODBUS_CFG	"CMSE#CHCONFIGCLEAR"
#define SMS_CLEAR_TCPBACKUP		"CMSE#CLEAR#TCPBACKUP"

#define SMS_DEVICE_RESET		"CMSE#RST"
#define SMS_START_DOTA			"CMSE#DOTA#"

//Max size of SMS.
#define SMS_TEXT_MAX_SIZE		200
//Minimum seconds for the peritime.
#define PERI_TIME_MINIMUM		15


//Globals.
void usfn_CheckSMS(void);
void usfn_SendSms(char*, char*);
#endif
